#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : spyder
Version  : 3.2.5
Release  : 2
URL      : https://pypi.python.org/packages/b9/0f/dbdd4390adf85239e16eec1821b74389604163132f8e47aa2a9c6569d4a8/spyder-3.2.5.tar.gz
Source0  : https://pypi.python.org/packages/b9/0f/dbdd4390adf85239e16eec1821b74389604163132f8e47aa2a9c6569d4a8/spyder-3.2.5.tar.gz
Summary  : Scientific PYthon Development EnviRonment
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: spyder-bin
Requires: spyder-python3
Requires: spyder-data
Requires: spyder-python
Requires: PyQt5
Requires: Pygments
Requires: QtAwesome
Requires: QtPy
Requires: Sphinx
Requires: chardet
Requires: cloudpickle
Requires: jedi
Requires: nbconvert
Requires: numpydoc
Requires: pickleshare
Requires: psutil
Requires: pycodestyle
Requires: pyflakes
Requires: pylint
Requires: pyzmq
Requires: qtconsole
Requires: rope
BuildRequires : PyQt5
BuildRequires : Pygments
BuildRequires : QtAwesome
BuildRequires : QtPy
BuildRequires : Sphinx
BuildRequires : chardet
BuildRequires : cloudpickle
BuildRequires : jedi
BuildRequires : nbconvert
BuildRequires : numpydoc
BuildRequires : pbr
BuildRequires : pickleshare
BuildRequires : pip
BuildRequires : psutil
BuildRequires : pycodestyle
BuildRequires : pyflakes
BuildRequires : pylint
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : pyzmq
BuildRequires : qtconsole
BuildRequires : rope
BuildRequires : setuptools

%description
MATLAB-like features in a simple and light-weighted software.
        It also provides ready-to-use pure-Python widgets to your PyQt5 or

%package bin
Summary: bin components for the spyder package.
Group: Binaries
Requires: spyder-data

%description bin
bin components for the spyder package.


%package data
Summary: data components for the spyder package.
Group: Data

%description data
data components for the spyder package.


%package python
Summary: python components for the spyder package.
Group: Default
Requires: spyder-python3

%description python
python components for the spyder package.


%package python3
Summary: python3 components for the spyder package.
Group: Default
Requires: python3-core

%description python3
python3 components for the spyder package.


%prep
%setup -q -n spyder-3.2.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1515342636
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/spyder3
/usr/bin/spyder_win_post_install.py

%files data
%defattr(-,root,root,-)
/usr/share/applications/spyder3.desktop
/usr/share/metainfo/spyder3.appdata.xml
/usr/share/pixmaps/spyder3.png

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
